import 'dart:io';

import 'package:privacy_ledger/models/sdk_entry.dart';

/// A merged row for one distinct data type across all matched SDKs.
class PlayDataSafetyRow {
  final String dataType;
  final bool sharedWithThirdParties;
  final Set<String> purposes;
  final bool optional;
  final bool encryptedInTransit;
  final bool userCanRequestDeletion;
  final List<String> collectedBySdks;

  const PlayDataSafetyRow({
    required this.dataType,
    required this.sharedWithThirdParties,
    required this.purposes,
    required this.optional,
    required this.encryptedInTransit,
    required this.userCanRequestDeletion,
    required this.collectedBySdks,
  });
}

/// Generates a Markdown checklist mirroring Google Play Console's Data Safety form.
///
/// Purpose category names match Play Console's published list:
/// https://support.google.com/googleplay/android-developer/answer/10787469
class PlayDatasafetyGenerator {
  /// Maps our YAML `purpose` values to Play Console purpose category labels.
  static const Map<String, String> purposeToPlay = {
    'advertising': 'Advertising or marketing',
    'analytics': 'Analytics',
    'app_functionality': 'App functionality',
    'fraud_prevention': 'Fraud prevention, security, and compliance',
    'developer_communications': 'Developer communications',
    'personalization': 'Personalization',
    'account_management': 'Account management',
  };

  /// Human-readable labels for our internal data type keys.
  static const Map<String, String> dataTypeLabels = {
    'device_id': 'Device or other IDs',
    'user_id': 'User IDs',
    'approximate_location': 'Approximate location',
    'coarse_location': 'Approximate location',
    'precise_location': 'Precise location',
    'purchase_history': 'Purchase history',
    'payment_info': 'Payment info / credit card / financial',
    'crash_data': 'Crash logs',
    'performance_data': 'Performance data (diagnostics)',
    'diagnostics': 'Diagnostics / other app performance data',
    'advertising_data': 'Advertising data / other advertising IDs',
    'product_interaction': 'App interactions',
    'email': 'Email address',
    'name': 'Name',
    'phone_number': 'Phone number',
    'photos': 'Photos',
    'videos': 'Videos',
    'files_and_docs': 'Files and docs',
    'biometric': 'Biometric data',
  };

  List<PlayDataSafetyRow> buildRows(List<SdkEntry> sdks) {
    // Keyed by data type string — merge across SDKs.
    final map = <String, _Agg>{};

    for (final sdk in sdks) {
      for (final item in sdk.dataCollected) {
        final agg = map.putIfAbsent(item.type, () => _Agg(type: item.type));
        if (!agg.sdkNames.contains(sdk.displayName)) {
          agg.sdkNames.add(sdk.displayName);
        }
        if (item.sharedWithThirdParties) agg.shared = true;
        // If ANY SDK collects it as required, mark required (optional = false).
        if (!item.optional) agg.optional = false;
        // Encrypted / deletion: AND across SDKs (conservative — false if any says no).
        if (!sdk.encryptedInTransit) agg.encrypted = false;
        if (!sdk.userCanRequestDeletion) agg.canDelete = false;
        agg.purposes.add(purposeToPlay[item.purpose] ?? item.purpose);
      }
    }

    final rows =
        map.values
            .map(
              (a) => PlayDataSafetyRow(
                dataType: a.type,
                sharedWithThirdParties: a.shared,
                purposes: a.purposes,
                optional: a.optional,
                encryptedInTransit: a.encrypted,
                userCanRequestDeletion: a.canDelete,
                collectedBySdks: List.unmodifiable(a.sdkNames),
              ),
            )
            .toList()
          ..sort((a, b) => a.dataType.compareTo(b.dataType));

    return rows;
  }

  String generateMarkdown(List<SdkEntry> sdks) {
    final rows = buildRows(sdks);
    final buffer = StringBuffer();

    buffer.writeln('# Google Play Data Safety Checklist');
    buffer.writeln();
    buffer.writeln(
      '_Generated by privacy_ledger. Verify every answer against Play Console '
      'and each SDK\'s current docs before submitting. This is not legal advice._',
    );
    buffer.writeln();
    buffer.writeln(
      'Play Console purpose categories used below '
      '(https://support.google.com/googleplay/android-developer/answer/10787469):',
    );
    buffer.writeln('- App functionality');
    buffer.writeln('- Analytics');
    buffer.writeln('- Developer communications');
    buffer.writeln('- Fraud prevention, security, and compliance');
    buffer.writeln('- Advertising or marketing');
    buffer.writeln('- Personalization');
    buffer.writeln('- Account management');
    buffer.writeln();

    if (rows.isEmpty) {
      buffer.writeln(
        'No known data-collecting SDKs matched. Nothing to declare '
        'from the database — still review your own app code.',
      );
      return buffer.toString();
    }

    for (final row in rows) {
      final label = dataTypeLabels[row.dataType] ?? row.dataType;
      buffer.writeln('## $label');
      buffer.writeln();
      buffer.writeln('- **Data type (internal key):** `${row.dataType}`');
      buffer.writeln('- **Collected?** Yes');
      buffer.writeln(
        '- **Shared with third parties?** '
        '${row.sharedWithThirdParties ? 'Yes' : 'No'}',
      );
      buffer.writeln('- **Purpose:** ${row.purposes.toList()..sort()}');
      buffer.writeln(
        '- **Is this data optional or required?** '
        '${row.optional ? 'Optional' : 'Required (users cannot opt out of this collection while using these features)'}',
      );
      buffer.writeln(
        '- **Encrypted in transit?** '
        '${row.encryptedInTransit ? 'Yes' : 'No / verify'}',
      );
      buffer.writeln(
        '- **Can users request data deletion?** '
        '${row.userCanRequestDeletion ? 'Yes' : 'No / verify'}',
      );
      if (row.collectedBySdks.length > 1) {
        buffer.writeln(
          '- **Collected by multiple SDKs:** '
          '${row.collectedBySdks.join(', ')}',
        );
      } else {
        buffer.writeln('- **Collected by:** ${row.collectedBySdks.join(', ')}');
      }
      buffer.writeln();
    }

    return buffer.toString();
  }

  void writeToFile(List<SdkEntry> sdks, String outputPath) {
    final file = File(outputPath);
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(generateMarkdown(sdks));
  }
}

class _Agg {
  final String type;
  final List<String> sdkNames = [];
  final Set<String> purposes = {};
  bool shared = false;
  bool optional = true; // starts true; any required item flips to false
  bool encrypted = true;
  bool canDelete = true;

  _Agg({required this.type});
}
