import 'dart:io';

import 'package:privacy_ledger/models/sdk_entry.dart';

/// Generates a plain-English privacy-policy paragraph from matched SDKs.
class PolicySummaryGenerator {
  static const Map<String, String> _purposeGroupLabels = {
    'advertising': 'advertising',
    'analytics': 'analytics',
    'app_functionality': 'app functionality',
    'fraud_prevention': 'fraud prevention and security',
    'personalization': 'personalization',
    'developer_communications': 'developer communications',
    'account_management': 'account management',
  };

  static const Map<String, String> _dataTypePhrases = {
    'device_id': 'device identifiers',
    'user_id': 'user identifiers',
    'approximate_location': 'approximate location (derived from IP address)',
    'coarse_location': 'approximate location',
    'precise_location': 'precise location',
    'purchase_history': 'purchase history',
    'payment_info': 'payment information',
    'crash_data': 'crash logs',
    'performance_data': 'app performance data',
    'diagnostics': 'diagnostic data',
    'advertising_data': 'advertising interaction data',
    'product_interaction': 'how you interact with the app',
    'email': 'email address',
    'name': 'name',
    'phone_number': 'phone number',
    'photos': 'photos',
    'videos': 'videos',
    'files_and_docs': 'files and documents',
    'biometric': 'biometric authentication signals (processed on-device)',
  };

  String generate(List<SdkEntry> sdks) {
    if (sdks.isEmpty) {
      return 'This app does not currently declare third-party SDK data '
          'collection through privacy_ledger. Review your own code and any '
          'SDKs not yet in the database before publishing a privacy policy.\n';
    }

    // Group data types by purpose (not by SDK).
    final byPurpose = <String, Set<String>>{};
    final allTypes = <String>{};
    var anyShared = false;
    var anyEncrypted = true;
    var anyDeletion = true;

    for (final sdk in sdks) {
      if (!sdk.encryptedInTransit) anyEncrypted = false;
      if (!sdk.userCanRequestDeletion) anyDeletion = false;
      for (final item in sdk.dataCollected) {
        allTypes.add(item.type);
        byPurpose.putIfAbsent(item.purpose, () => <String>{}).add(item.type);
        if (item.sharedWithThirdParties) anyShared = true;
      }
    }

    final buffer = StringBuffer();
    buffer.writeln('# Privacy summary');
    buffer.writeln();
    buffer.write(
      'This app uses third-party services that help it run, measure usage, '
      'and (where applicable) show ads or process in-app purchases. ',
    );

    final purposeOrder = [
      'app_functionality',
      'analytics',
      'advertising',
      'fraud_prevention',
      'personalization',
      'developer_communications',
      'account_management',
    ];

    final sentences = <String>[];
    for (final purpose in purposeOrder) {
      final types = byPurpose[purpose];
      if (types == null || types.isEmpty) continue;
      final label = _purposeGroupLabels[purpose] ?? purpose;
      final phrases = types.map((t) => _dataTypePhrases[t] ?? t).toList()
        ..sort();
      sentences.add('For $label, it may collect ${_joinAnd(phrases)}');
    }
    // Any purposes not in the ordered list.
    for (final entry in byPurpose.entries) {
      if (purposeOrder.contains(entry.key)) continue;
      final label = _purposeGroupLabels[entry.key] ?? entry.key;
      final phrases = entry.value.map((t) => _dataTypePhrases[t] ?? t).toList()
        ..sort();
      sentences.add('For $label, it may collect ${_joinAnd(phrases)}');
    }

    if (sentences.isNotEmpty) {
      buffer.write(sentences.join('. '));
      buffer.write('. ');
    }

    if (anyShared) {
      buffer.write(
        'Some of this information is processed by third-party providers '
        'that power those features. ',
      );
    }

    if (anyEncrypted) {
      buffer.write('Data is transmitted using encryption in transit. ');
    } else {
      buffer.write(
        'Confirm with each provider whether data is encrypted in transit. ',
      );
    }

    if (anyDeletion) {
      buffer.write(
        'Where the providers support it, you can request deletion of data '
        'associated with your use of the app. ',
      );
    } else {
      buffer.write(
        'Deletion support varies by provider — see the full privacy policy '
        'for how to request deletion. ',
      );
    }

    buffer.writeln();
    buffer.writeln();
    buffer.writeln(
      '_This paragraph was generated by privacy_ledger from known SDK '
      'database entries. It is a starting draft for a hosted privacy policy, '
      'not a substitute for legal review._',
    );
    buffer.writeln();

    // Ensure we have a machine-checkable list of distinct types for tests.
    buffer.writeln('<!-- data_types: ${allTypes.toList()..sort()} -->');

    return buffer.toString();
  }

  void writeToFile(List<SdkEntry> sdks, String outputPath) {
    final file = File(outputPath);
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(generate(sdks));
  }

  static String _joinAnd(List<String> items) {
    if (items.isEmpty) return '';
    if (items.length == 1) return items.first;
    if (items.length == 2) return '${items[0]} and ${items[1]}';
    return '${items.sublist(0, items.length - 1).join(', ')}, and ${items.last}';
  }
}
